/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolveRouteImport } from './routes/solve'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuddiesRouteImport } from './routes/buddies'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const SolveRoute = SolveRouteImport.update({
  id: '/solve',
  path: '/solve',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddiesRoute = BuddiesRouteImport.update({
  id: '/buddies',
  path: '/buddies',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/buddies': typeof BuddiesRoute
  '/dashboard': typeof DashboardRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/solve': typeof SolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/buddies': typeof BuddiesRoute
  '/dashboard': typeof DashboardRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/solve': typeof SolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/buddies': typeof BuddiesRoute
  '/dashboard': typeof DashboardRoute
  '/focus': typeof FocusRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/solve': typeof SolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/badges'
    | '/buddies'
    | '/dashboard'
    | '/focus'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/solve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/badges'
    | '/buddies'
    | '/dashboard'
    | '/focus'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/solve'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/badges'
    | '/buddies'
    | '/dashboard'
    | '/focus'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/solve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BadgesRoute: typeof BadgesRoute
  BuddiesRoute: typeof BuddiesRoute
  DashboardRoute: typeof DashboardRoute
  FocusRoute: typeof FocusRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  SolveRoute: typeof SolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solve': {
      id: '/solve'
      path: '/solve'
      fullPath: '/solve'
      preLoaderRoute: typeof SolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddies': {
      id: '/buddies'
      path: '/buddies'
      fullPath: '/buddies'
      preLoaderRoute: typeof BuddiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BadgesRoute: BadgesRoute,
  BuddiesRoute: BuddiesRoute,
  DashboardRoute: DashboardRoute,
  FocusRoute: FocusRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  SolveRoute: SolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
